version: "3"

networks:
    default:
        external: false

services:
    hpl:
        image: hpl
        networks:
            - default
        ports:
            - "2222:22"
        volumes:
            - /home/ubuntu/.ssh/:/root/.ssh/:ro