version: "3"

networks:
    default:
        external: false

services:
    hpl:
        image: hpl
        networks:
            - default
        ports:
            - "2222:22"
        environment:
            - AUTHORIZED_KEYS=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCu9z26Jx9gtOv7IB60bhX/knWvTcuS66R67mGYqViE5G6Qev37/78B+hg+Hy1OqIMCQV37hNZX8z4JMJbOJZ187ChqCj0MeA9zSejUNyrZwJHhci3080xyuJbFVpC3vNmR4Jyh7DDWUpyQyHgcO0ot+l0Z1yP6dicWv1g2pDo36IlY7Xl4PRo6Ja0PGAtlXsID2yDXhtjaV7PkhA6bub0Vr4YfmrZSWmZ49P31eHWPUioG5B7IlrYX2UJ0uT/tDQhVIYv7AF7lGQG0bgkUeOxLeHI/s3S9y3prQvEjWTez6AZeZrSoOezYO6iOM2+vKBqBPWU6YM60kFVCHCmWrW+64nMerfEEFpZ8jpon4F2CaD7WgPO7fXa6bIhX5Tr9IppEUgtK4eTIJ7W/lJk7VF+BX8yJ9PY0BH1FI4bf9LkhzAhpP6c9EN7j6ST3vxCZmmw2WGsbhvfFBaIXgaEZmCONnQU/fuZoOG/xFvTYv6f8KNU+lK2ul/tGmkvLo1sYI8E= ex0dus@ex0blade
            - KNOWN_HOSTS=|1|chmteLWVpuPjmsWcc2QTsSQiJyU=|sujSoaeuFPgkkH++QReg1+tT1zg= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCHC3twX2uguq205pbiMMcANTkUi+yh4i42iVN0K88nrOF2zr11//m4W3hUJph76ZJrHM0c2CiFVVCiZTyo7E+g=
